"""Service for book operations."""

from sqlalchemy.orm import Session

from app.models.book import Book
from app.schemas.book import BookRequest, BookResponse


def create_book(db: Session, book: BookRequest) -> BookResponse:
    """Create a new book (lending or trading portfolio).

    Args:
        db: Database session
        book: Book creation schema

    Returns:
        BookRead schema with created book data
    """
    db_book = Book(
        id=None,  # Will be generated by database if using UUID
        name=book.name,
        currency=book.currency,
    )
    db.add(db_book)
    db.commit()
    db.refresh(db_book)
    return BookResponse.model_validate(db_book)


def get_book(db: Session, book_id: str) -> BookResponse | None:
    """Get a book by ID.

    Args:
        db: Database session
        book_id: Book ID to retrieve

    Returns:
        BookRead schema if found, None otherwise
    """
    db_book = db.query(Book).filter(Book.id == book_id).first()
    if db_book is None:
        return None
    return BookResponse.model_validate(db_book)


def list_books(db: Session) -> list[BookResponse]:
    """List all books.

    Args:
        db: Database session

    Returns:
        List of BookRead schemas
    """
    db_books = db.query(Book).all()
    return [BookResponse.model_validate(b) for b in db_books]
