"""Service for client operations."""

from sqlalchemy.orm import Session

from app.models.client import Client
from app.schemas.client import ClientRequest, ClientResponse


def create_client(db: Session, client: ClientRequest) -> ClientResponse:
    """Create a new client.

    Args:
        db: Database session
        client: Client creation schema

    Returns:
        ClientRead schema with created client data
    """
    db_client = Client(
        id=None,  # Will be generated by database if using UUID
        name=client.name,
        country=client.country,
        risk_rating=client.risk_rating,
    )
    db.add(db_client)
    db.commit()
    db.refresh(db_client)
    return ClientResponse.model_validate(db_client)


def get_client(db: Session, client_id: str) -> ClientResponse | None:
    """Get a client by ID.

    Args:
        db: Database session
        client_id: Client ID to retrieve

    Returns:
        ClientRead schema if found, None otherwise
    """
    db_client = db.query(Client).filter(Client.id == client_id).first()
    if db_client is None:
        return None
    return ClientResponse.model_validate(db_client)


def list_clients(db: Session) -> list[ClientResponse]:
    """List all clients.

    Args:
        db: Database session

    Returns:
        List of ClientRead schemas
    """
    db_clients = db.query(Client).all()
    return [ClientResponse.model_validate(c) for c in db_clients]
