"""Service for collateral operations."""

from sqlalchemy.orm import Session

from app.models.collateral import Collateral
from app.schemas.collateral import CollateralRequest, CollateralResponse


def create_collateral(db: Session, collateral: CollateralRequest) -> CollateralResponse:
    """Create new collateral for a loan.

    Args:
        db: Database session
        collateral: Collateral creation schema

    Returns:
        CollateralRead schema with created collateral data
    """
    db_collateral = Collateral(
        id=None,  # Will be generated by database if using UUID
        loan_id=collateral.loan_id,
        asset_type=collateral.asset_type,
        asset_name=collateral.asset_name,
        market_value=collateral.market_value,
        currency=collateral.currency,
        haircut=collateral.haircut_percentage,
    )
    db.add(db_collateral)
    db.commit()
    db.refresh(db_collateral)
    return CollateralResponse.model_validate(db_collateral)


def get_collateral(db: Session, collateral_id: str) -> CollateralResponse | None:
    """Get collateral by ID.

    Args:
        db: Database session
        collateral_id: Collateral ID to retrieve

    Returns:
        CollateralRead schema if found, None otherwise
    """
    db_collateral = (
        db.query(Collateral).filter(Collateral.id == collateral_id).first()
    )
    if db_collateral is None:
        return None
    return CollateralResponse.model_validate(db_collateral)


def list_collateral(db: Session) -> list[CollateralResponse]:
    """List all collateral items.

    Args:
        db: Database session

    Returns:
        List of CollateralRead schemas
    """
    db_collateral = db.query(Collateral).all()
    return [CollateralResponse.model_validate(c) for c in db_collateral]


def list_collateral_by_loan(db: Session, loan_id: str) -> list[CollateralResponse]:
    """List all collateral items for a specific loan.

    Args:
        db: Database session
        loan_id: Loan ID to filter by

    Returns:
        List of CollateralRead schemas for the loan
    """
    db_collateral = db.query(Collateral).filter(Collateral.loan_id == loan_id).all()
    return [CollateralResponse.model_validate(c) for c in db_collateral]

def _to_collateral_response(collateral: Collateral) -> CollateralResponse:
    return CollateralResponse.model_validate(collateral)
