"""Service for loan operations."""

from sqlalchemy.orm import Session

from app.models.loan import Loan
from app.schemas.loan import LoanRequest, LoanResponse


def create_loan(db: Session, loan: LoanRequest) -> LoanResponse:
    """Create a new loan.

    Args:
        db: Database session
        loan: Loan creation schema

    Returns:
        LoanRead schema with created loan data
    """
    db_loan = Loan(
        id=None,  # Will be generated by database if using UUID
        client_id=loan.client_id,
        book_id=loan.book_id,
        amount=loan.amount,
        currency=loan.currency,
    )
    db.add(db_loan)
    db.commit()
    db.refresh(db_loan)
    return LoanResponse.model_validate(db_loan)


def get_loan(db: Session, loan_id: str) -> LoanResponse | None:
    """Get a loan by ID.

    Args:
        db: Database session
        loan_id: Loan ID to retrieve

    Returns:
        LoanRead schema if found, None otherwise
    """
    db_loan = db.query(Loan).filter(Loan.id == loan_id).first()
    if db_loan is None:
        return None
    return LoanResponse.model_validate(db_loan)


def list_loans(db: Session) -> list[LoanResponse]:
    """List all loans.

    Args:
        db: Database session

    Returns:
        List of LoanRead schemas
    """
    db_loans = db.query(Loan).all()
    return [LoanResponse.model_validate(l) for l in db_loans]


def list_loans_by_client(db: Session, client_id: str) -> list[LoanResponse]:
    """List all loans for a specific client.

    Args:
        db: Database session
        client_id: Client ID to filter by

    Returns:
        List of LoanRead schemas for the client
    """
    db_loans = db.query(Loan).filter(Loan.client_id == client_id).all()
    return [LoanResponse.model_validate(l) for l in db_loans]


def list_loans_by_book(db: Session, book_id: str) -> list[LoanResponse]:
    """List all loans in a specific book.

    Args:
        db: Database session
        book_id: Book ID to filter by

    Returns:
        List of LoanRead schemas for the book
    """
    db_loans = db.query(Loan).filter(Loan.book_id == book_id).all()
    return [LoanResponse.model_validate(l) for l in db_loans]
