"""add scenario runs

Revision ID: 127a7bd390f3
Revises: b965cf1723f2
Create Date: 2026-06-15 22:34:15.944459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127a7bd390f3'
down_revision: Union[str, Sequence[str], None] = 'b965cf1723f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_name', sa.String(), nullable=False),
    sa.Column('asset_type_shocks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_total_loan_exposure', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_total_collateral_market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_total_eligible_collateral_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_weighted_ltv', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('base_risk_status', sa.String(), nullable=False),
    sa.Column('stressed_total_collateral_market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stressed_total_eligible_collateral_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stressed_weighted_ltv', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stressed_risk_status', sa.String(), nullable=False),
    sa.Column('base_total_position_market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stressed_total_position_market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_runs')
    # ### end Alembic commands ###
