"""add trade order execution fields

Revision ID: b965cf1723f2
Revises: f0fb929721cb
Create Date: 2026-06-08 22:54:07.913450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b965cf1723f2'
down_revision: Union[str, Sequence[str], None] = 'f0fb929721cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_orders', sa.Column('execution_price', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('trade_orders', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_orders', 'executed_at')
    op.drop_column('trade_orders', 'execution_price')
    # ### end Alembic commands ###
